# Generated by Django 3.2.13 on 2023-01-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'basket', 'verbose_name_plural': 'baskets'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
